import FaviconUpdater from './components/FaviconUpdater'; // Import the client component
import { Inter } from "next/font/google";
import "./globals.css";
import { Metadata } from "next";
import { AuthProvider } from './components/AuthContext';

const inter = Inter({ subsets: ["latin"] });

// This is for server-side metadata
export const metadata: Metadata = {
  title: "test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* Default favicon */}
        <link rel="icon" href="/images/light.png" />
      </head>
      <body>
        <FaviconUpdater />  {/* Include the client-side logic */}
        <AuthProvider>
        {children}
        </AuthProvider>
      </body>
    </html>
  );
}
